// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:89a192fa-b923-4f8e-a874-60e83d88526d",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Tg9cJBzPp",
    "aws_user_pools_web_client_id": "4pteqc6rj7rka2303a79akvhls",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "gamedemodynamodb",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "gamesdemobucket",
    "aws_user_files_s3_bucket_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "gamesapi",
            "endpoint": "https://sr3arlw09j.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://7ansecvq2jcajkaz4jhl25vone.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5g5rwvuqzzfyfiadtxat74blty",
    "aws_mobile_analytics_app_id": "f7dc8e2658d942bf841fb085479f7eb4",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
