// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cloud_logic_custom": [
        {
            "name": "gamesapi",
            "endpoint": "https://298p1l6yil.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "gamesdb",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
